(** Warning generated by static analazyer *)

type t = { linenr: int; column: int; id: string; msg: string; } [@@deriving yojson]

val mk : int -> int -> string -> string  -> t

val to_string : t -> string
(** Converts warning to string *)
